import os
import datetime

SQLALCHEMY_DATABASE_URI = os.environ.get('SQLALCHEMY_DATABASE_URI')
SECRET_KEY = os.environ.get('SECRET_KEY')
SQLALCHEMY_TRACK_MODIFICATIONS = os.environ.get('SQLALCHEMY_TRACK_MODIFICATIONS')
JWT_SECRET_KEY = os.environ.get('JWT_SECRET_KEY')
FLASK_ADMIN_SWATCH = os.environ.get('FLASK_ADMIN_SWATCH')
JWT_ACCESS_TOKEN_EXPIRES = datetime.timedelta(hours=3)
